export interface Movie {
	id: number,
	title: string,
	genre: string[],
	releaseYear: number,
	director: string,
	actors: string[],
	annotation?: string,
	image?: string,
	createdYear: Date,
	updatedYear: Date,
}

export const MOVIES_MOCK: Movie[] = [
	{
		id: 1,
		title: 'Матрица',
		genre: ['Фантастика'],
		releaseYear: 1996,
		director: 'Вачовски',
		actors: ['Киану Ривз', 'Лоренс Фишбёрн'],
		annotation: 'Жизнь Томаса Андерсона разделена на две части: Хакер Нео узнает, что его мир — виртуальный. Выдающийся экшен, доказавший, что зрелищное кино может быть умным.',
		image: './assets/img/matrix.png',
		createdYear: new Date(),
		updatedYear: new Date(),
	},
	{
		id: 2,
		title: 'Начало',
		genre: ['Фантастика', 'Триллер'],
		releaseYear: 2010,
		director: 'Кристофер Нолан',
		actors: ['Леонардо ДиКаприо', 'Джозеф Гордон-Левитт'],
		annotation: 'Группа воров проникает в сны людей для кражи и внедрения идей.',
		image: './assets/img/start.png',
		createdYear: new Date(),
		updatedYear: new Date(),
	},
	{
		id: 3,
		title: 'Форрест Гамп',
		genre: ['Драма', 'Комедия'],
		releaseYear: 1994,
		director: 'Роберт Земекис',
		actors: ['Том Хэнкс', 'Робин Райт'],
		annotation: 'История жизни необычного человека, который несмотря на свои особенности добивается успеха.',
		image: './assets/img/forest.png',
		createdYear: new Date(),
		updatedYear: new Date(),
	},
	{
		id: 4,
		title: 'Интерстеллар',
		genre: ['Фантастика', 'Драма'],
		releaseYear: 2014,
		director: 'Кристофер Нолан',
		actors: ['Мэттью Макконахи', 'Энн Хэтэуэй'],
		annotation: 'Команда исследователей отправляется в космос для поиска нового дома для человечества.',
		image: '',
		createdYear: new Date(),
		updatedYear: new Date(),
	},
	{
		id: 5,
		title: 'Темный рыцарь',
		genre: ['Экшн', 'Криминал'],
		releaseYear: 2008,
		director: 'Кристофер Нолан',
		actors: ['Кристиан Бейл', 'Хит Леджер'],
		annotation: 'Бэтмен должен противостоять Джокеру, который сеет хаос в Готэме.',
		image: '',
		createdYear: new Date(),
		updatedYear: new Date(),
	},
	{
		id: 6,
		title: 'Зеленая миля',
		genre: ['Драма', 'Фэнтези'],
		releaseYear: 1999,
		director: 'Фрэнк Дарабонт',
		actors: ['Том Хэнкс', 'Майкл Кларк Дункан'],
		annotation: 'Тюремный охранник обнаруживает сверхъестественные способности у заключенного.',
		image: '',
		createdYear: new Date(),
		updatedYear: new Date(),
	},
	{
		id: 7,
		title: 'Криминальное чтиво',
		genre: ['Криминал', 'Комедия'],
		releaseYear: 1994,
		director: 'Квентин Тарантино',
		actors: ['Джон Траволта', 'Ума Турман', 'Сэмюэл Л. Джексон'],
		annotation: 'Истории наемных убийц, боксеров и гангстеров переплетаются в сюрреалистичном мире.',
		image: '',
		createdYear: new Date(),
		updatedYear: new Date(),
	}
];
